function [symbols, err_ratio] = conv_receive(signal, ending, efficiency, ...
                                             crc_poly, hard)
    [symbols, err_ratio] = conv_decode(signal, ending, efficiency, crc_poly, ...
                                       hard);
end
