function [symbols, err_rate] = conv_receive(signal, ending, efficiency, ...
                                            crc_poly, hard)
    [symbols, err_rate] = conv_decode(signal, ending, efficiency, crc_poly, ...
                                      hard);
end
