symbols = randi([0 1], 10, 1);
trellis_2 = poly2trellis(4, [15, 17]);      % 1/2.
trellis_3 = poly2trellis(4, [13, 15, 17]);  % 1/3.

assert_decode = @(real_symbols, expected_symbols, description) ...
    assert(all(size(real_symbols) == size(expected_symbols)) && ...
           all(real_symbols == expected_symbols), ...
           ['Assertion failed: ' description '\n' ...
            'Expected: %s\n' ...
            'Real: %s\n'], ...
           mat2str(expected_symbols), mat2str(real_symbols));

% No ending, no CRC, hard.
signal_2 = sym_encode(convenc(symbols, trellis_2), 2);
signal_3 = sym_encode(convenc(symbols, trellis_3), 3);

assert_decode(conv_decode(signal_2, false, 2, [], true), ...
              symbols, ...
              'conv_decode, 1/2, no ending, no CRC, hard');
assert_decode(conv_decode(signal_3, false, 3, [], true), ...
              symbols, ...
              'conv_decode, 1/3, no ending, no CRC, hard');

% With ending, no CRC, hard.
symbols_with_ending = [symbols; zeros(3, 1)];
signal_2 = sym_encode(convenc(symbols_with_ending, trellis_2), 2);
signal_3 = sym_encode(convenc(symbols_with_ending, trellis_3), 3);

assert_decode(conv_decode(signal_2, true, 2, [], true), ...
              symbols, ...
              'conv_decode, 1/2, with ending, no CRC, hard');
assert_decode(conv_decode(signal_3, true, 3, [], true), ...
              symbols, ...
              'conv_decode, 1/3, with ending, no CRC, hard');
